Parameters:
  BucketNameParameter:
    Type: String
    Default: nccid-data-warehouse
    Description: The base name of the storage bucket

Resources:

  # Main bucket
  WarehouseBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref "BucketNameParameter"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled

  # IAM
  UploadToRawPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["upload-to-", !Ref "BucketNameParameter", "-raw"]]
      Description: Allow uploading to the raw prefix in the warehouse bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:PutObject"
            Resource:
              !Join ["", [!GetAtt [WarehouseBucket, Arn], "/raw-${aws:username}/*"]]
  DataUploaderGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref UploadToRawPolicy

  ETLPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["etl-", !Ref "BucketNameParameter"]]
      Description: Allow ETL operations on the non-raw prefixes in the warehouse bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
            Resource:
              !GetAtt [WarehouseBucket, Arn]
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              !Join ["", [!GetAtt [WarehouseBucket, Arn], "/*"]]
          - Effect: Allow
            Action:
              - "s3:PutObject"
            Resource:
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/validation/*"]]
  ETLGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref ETLPolicy

  ReadOnlyAccessWholeBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["read-only-", !Ref "BucketNameParameter"]]
      Description: Allow read-only view of the warehouse bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              !GetAtt [WarehouseBucket, Arn]
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              !Join ["", [!GetAtt [WarehouseBucket, Arn], "/*"]]
  DataVerifierGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref ReadOnlyAccessWholeBucketPolicy

  TrainingCTPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["training-ct-", !Ref "BucketNameParameter"]]
      Description: Allow reading the CT and patient data sections of the training set
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:HeadBucket"
            Resource:
              !GetAtt [WarehouseBucket, Arn]
            Condition:
              StringLike:
                s3:prefix: ["training/ct/*", "training/ct-metadata/*", "training/data/*"]
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/ct/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/ct-metadata/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/data/*"]]
  TrainingCTGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref TrainingCTPolicy

  TrainingMRIPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["training-mri-", !Ref "BucketNameParameter"]]
      Description: Allow reading the MRI and patient data sections of the training set
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:HeadBucket"
            Resource:
              !GetAtt [WarehouseBucket, Arn]
            Condition:
              StringLike:
                s3:prefix: ["training/mri/*", "training/mri-metadata/*", "training/data/*"]
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/mri/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/mri-metadata/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/data/*"]]
  TrainingMRIGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref TrainingMRIPolicy

  TrainingXrayPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["training-xray-", !Ref "BucketNameParameter"]]
      Description: Allow reading the X-ray and patient data sections of the training set
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:HeadBucket"
            Resource:
              !GetAtt [WarehouseBucket, Arn]
            Condition:
              StringLike:
                s3:prefix: ["training/x-ray/*", "training/x-ray-metadata/*", "training/data/*"]
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/x-ray/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/x-ray-metadata/*"]]
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/data/*"]]
  TrainingXrayGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref TrainingXrayPolicy

  TrainingAllPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", ["training-all-", !Ref "BucketNameParameter"]]
      Description: Allow reading all data in the training set
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:HeadBucket"
            Resource:
              !GetAtt [WarehouseBucket, Arn]
            Condition:
              StringLike:
                s3:prefix: ["training/*"]
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/training/*"]]
  TrainingAllGroup:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - !Ref TrainingAllPolicy

  # CloudTrail
  CloudTrailLogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join ["", [!Ref "BucketNameParameter", "-object-logs"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
  CloudTrailLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailLogsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt [CloudTrailLogsBucket, Arn]
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Join ["", [!GetAtt [CloudTrailLogsBucket, Arn], "/AWSLogs/",!Ref "AWS::AccountId", "/*"]]
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  CloudTrailLogs:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      # Have to explicitly pass the dependency on the bucket policy, otherwise
      # they both get created at the same time and the trail creation fails
      - CloudTrailLogsBucketPolicy
    Properties:
      IsLogging: true
      S3BucketName: !Ref CloudTrailLogsBucket
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Join ["", [!GetAtt [WarehouseBucket, Arn], "/"]]
