name: Warehouse Loader Checks

on: [push]

jobs:
  warehouse-loader:

    runs-on: ubuntu-latest
    env:
      working-directory: ./warehouse-loader
    strategy:
      matrix:
        python: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: "Python version"
      run: python -V

    - name: Install dependencies
      working-directory: ${{ env.working-directory }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Lint with black
      working-directory: ${{ env.working-directory }}
      run: |
        tox -e black

    - name: Lint with flake8
      working-directory: ${{ env.working-directory }}
      run: |
        tox -e flake8

    - name: Run tests
      working-directory: ${{ env.working-directory }}
      run: |
        tox -e py
