name:  Build and Preview Docs

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/site-preview.yml'

jobs:
  preview:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Create deployment
        id: deployment
        run: |
          echo "Creating deployment for ref: $GITHUB_REF"
          API_RESPONSE=$(curl -H "Accept: application/vnd.github.ant-man-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"ref": "'"$GITHUB_REF"'", "environment": "preview", "transient_environment": true, "description": "Docs preview", "required_contexts": []}' "https://api.github.com/repos/$GITHUB_REPOSITORY/deployments")
          STATUSES_URL=$(echo $API_RESPONSE | jq .statuses_url)
          echo "::set-output name=statuses_url::$STATUSES_URL"

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: |
          make html

      - name: Update deployment status (in_progress)
        run: |
          curl -H "Accept: application/vnd.github.flash-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"state": "in_progress"}' ${{ steps.deployment.outputs.statuses_url }}

      - name: Upload S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.working-directory }}
        run: |
          python3 -m pip install awscli
          aws s3 sync --delete build/html s3://${{ secrets.AWS_BUCKET }}/$GITHUB_SHA/

      - name: Update deployment status (success)
        if: success()
        run: |
          curl -H "Accept: application/vnd.github.ant-man-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"state": "success", "environment_url": "'"https://${{ secrets.AWS_BUCKET }}.s3.${{ secrets.AWS_BUCKET_REGION }}.amazonaws.com/${{ github.sha }}/index.html"'"}' ${{ steps.deployment.outputs.statuses_url }}

      - name: Update deployment status (success)
        if: failure()
        run: |
          curl -H "Accept: application/vnd.github.ant-man-preview+json" -H "Authorization: token ${{ github.token }}" -X POST -H 'Content-Type: application/json' -d '{"state": "failure"}' ${{ steps.deployment.outputs.statuses_url }}
